app/mod_inventory/views.py
# project/vendor/views.py

#################
#    imports    #
#################
import datetime
from flask import render_template, Blueprint, url_for, \
    redirect, flash, request

from flask.views import View

from flask_login import login_required

from ..models import db, Vendor, PurchaseOrder, LineItem, Component, Address,\
    Transaction, TagCategory, Tag, VendorComponent, TagManager

from forms import VendorCreateForm, PurchaseOrderForm, \
    ComponentCreateForm, TransactionForm, TagForm

################
#    config    #
################

inventory_blueprint = Blueprint('inventory',
                                __name__,
                                template_folder='templates')

################
#    views     #
################


class TransactionMakerView(View):
    methods = ["GET", "POST"]
    decorators = [login_required]

    def __init__(self, action_type):
        self.action_type = action_type

    def get_template_name(self):
        return '/inventory/transaction/make.html'

    def render_template(self, context):
        return render_template(self.get_template_name(), ** context)

    def dispatch_request(self):
        form = TransactionForm(request.form)
        form.component.choices = [(x.id, x.description)
                                  for x in Component.query.all()]
        if form.validate_on_submit():
            nt = Transaction()
            form.component.data = Component.query.get(form.component.data)
            nt.date_create = datetime.datetime.now()
            if request.form.get("checkout"):
                void = form.qty.data * (-1)
                if form.component.data.qty + void >= 0:
                    form.populate_obj(nt)
                    nt.component_id = form.component.data.id
                    nt.qty = void
                    db.session.add(nt)
                    db.session.commit()
                    flash('Success: Items Checked Out')
                else:
                    flash("Not enough items, only %s available" %
                          (form.component.data.qty))
                    form.component.data = form.component.data.id
                    return render_template("/inventory/transaction/make.html", form=form, the_action=self.action_type)
            elif request.form.get("checkin"):
                form.populate_obj(nt)
                nt.component_id = form.component.data.id
                nt.qty = form.qty.data
                db.session.add(nt)
                db.session.commit()
                flash('Success: %s Checked In' %
                      ("Items" if nt.qty > 1 else "Item"))
            return redirect(url_for('main.home'))
        return render_template("/inventory/transaction/make.html",
                               form=form, the_action=self.action_type)

################
#    routes    #
################
@inventory_blueprint.route('/transactions/', methods=['GET'])
@login_required
def transactions():
    page = request.args.get("page", 1)
    if page==u"":
        page=1
    else:
        page = int(page)
    period = request.args.get("period", None)
    search = request.args.get("search")
    query = Transaction.query.order_by(Transaction.date_create.desc())
    if search and search !="":
        period="all"
        query = query.filter(Transaction.notes.contains(search))
    if period == 'ten_days':
        period_date = datetime.datetime.now()
        time_delta = datetime.timedelta(days=-10)
        period_date = period_date + time_delta
        query = query.filter(Transaction.date_create > period_date)
    elif period == 'today':
        period_date = datetime.datetime.now()
        period_date = period_date.replace(hour=0, minute=0)
        query = query.filter(Transaction.date_create > period_date)
    elif period == 'month':
        period_date = datetime.date.today()
        period_date = period_date.replace(day=1)
        period_date = datetime.datetime.combine(period_date, datetime.datetime.min.time())
        query = query.filter(Transaction.date_create > period_date)
    transactions = query.paginate(page, per_page=20, error_out=True)
    return render_template("/inventory/transaction/transactions.html",
                           transactions=transactions, page=page, period=period, search=search)


inventory_blueprint.add_url_rule(
    '/transactions/check-in',
    view_func=TransactionMakerView.as_view('checkin', action_type='checkin'))
inventory_blueprint.add_url_rule(
    '/transactions/check-out',
    view_func=TransactionMakerView.as_view('checkout', action_type='checkout'))


################
#    Vendor    #
################


@inventory_blueprint.route('/inventory/vendor/<int:vendor_id>', methods=['GET'])
@inventory_blueprint.route('/inventory/vendor/', methods=['GET'])
@login_required
def view_vendor(vendor_id=None):
    if vendor_id:
        vendor = Vendor.query.get_or_404(vendor_id)
        orders = PurchaseOrder.query.filter_by(vendor_id=vendor.id)
        return render_template('inventory/vendor/view.html', vendor=vendor,
                               purchase_orders=orders)
    vendors = Vendor.query.all()
    return render_template('inventory/vendor/view_all.html', entries=vendors)


@inventory_blueprint.route('/inventory/vendor/create', methods=['GET', 'POST'])
@login_required
def create_vendor():
    form = VendorCreateForm()
    if form.validate_on_submit():
        vendor = Vendor.query.filter_by(name=form.name.data).first()
        address = Address.query.filter_by(line1=form.line1.data).first()
        with db.session.no_autoflush:
            if address is None:
                address = Address(line1=form.line1.data, line2=form.line2.data,
                                  city=form.city.data, state=form.state.data,
                                  zipcode=form.zipcode.data)
                db.session.add(address)
            if vendor is None:
                vendor = Vendor(name=form.name.data,
                                contact=form.contact.data,
                                phone=form.phone.data,
                                website=form.website.data,
                                address=address)
                db.session.add(vendor)
                db.session.commit()

                flash('New Vendor Added', 'success')
                return redirect(url_for('.view_vendor'))
            else:
                flash('Vendor already exist.')
                return redirect(url_for('.view_vendor'))
    return render_template('inventory/vendor/create.html', form=form)


@inventory_blueprint.route('/vendor/edit/<int:vendor_id>',
                           methods=['GET', 'POST'])
@login_required
def edit_vendor(vendor_id):
    vendor = Vendor.query.get_or_404(vendor_id)
    form = VendorCreateForm(obj=vendor)
    if form.validate_on_submit():
        form.populate_obj(vendor)
        db.session.commit()

        flash('Vendor Updated', 'success')
        return redirect(url_for('.view_vendor'))
    return render_template('inventory/vendor/edit.html', form=form)


#########################
#    Purchase Orders    #
#########################


@inventory_blueprint.route('/purchase_order/')
@inventory_blueprint.route('/purchase_order/<int:po_id>',
                           methods=['GET', 'POST'])
@login_required
def view_purchase_order(po_id=None):
    if po_id:
        order = PurchaseOrder.query.get_or_404(po_id)
        return render_template('inventory/purchase_order/view.html',
                               result=order)
    purchase_orders = PurchaseOrder.query.all()
    return render_template('inventory/purchase_order/view_all.html',
                           result=purchase_orders)


@inventory_blueprint.route('/purchase_order/create/<int:vendor_id>',
                           methods=['GET', 'POST'])
@login_required
def create_purchase_order(vendor_id):
    vendor = Vendor.query.get_or_404(vendor_id)
    form = PurchaseOrderForm()
    choices = [(x.id, x.description) for x in Component.query.all()]
    form.component.choices = choices if choices else [(0, 'None')]
    if form.validate_on_submit():
        with db.session.no_autoflush:
            order = PurchaseOrder()
            order.created_on = datetime.date.today()
            order.vendor = vendor
            order.user_id = form.user_id.data
            db.session.add(order)
            component = VendorComponent.query.filter_by(
                sku=form.sku.data).first()
            if component:
                line1 = LineItem(vendor_component=component,
                                 quantity=form.quantity.data,
                                 total_price=form.total_price.data)
                order.line_item.append(line1)
            else:
                flash('Component not found.')
                return render_template('inventory/purchase_order/create.html',
                                       form=form,
                                       vendor=vendor)
        db.session.commit()
        flash('Purchase Order Added', 'success')
        return redirect(url_for('.view_purchase_order', po_id=order.id))
    return render_template('inventory/purchase_order/create.html', form=form,
                           vendor=vendor)


@inventory_blueprint.route('/vendor/<int:vendor_id>/component/create',
                           methods=['GET', 'POST'])
@login_required
def create_vendor_component(vendor_id):
    vendor = Vendor.query.get_or_404(vendor_id)
    form = ComponentCreateForm()
    if form.validate_on_submit():
        component = VendorComponent.query.filter_by(sku=form.sku.data).first()
        if component is None:
            component = VendorComponent(sku=form.sku.data,
                                        description=form.description.data,
                                        vendor=vendor)
            db.session.add(component)
            db.session.commit()
            flash('New Component Added', 'success')

app/mod_main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from ..mod_user.forms import LoginForm

################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################

@login_required
@main_blueprint.route('/index')
def index():
    return render_template('user/index.html')

@main_blueprint.route('/')
def home():
	if current_user.is_authenticated():
		return redirect(url_for('main.index'))
	form = LoginForm()
	return render_template('main/home.html', form=form)


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

app/mod_user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from ..models import db, User, bcrypt
from forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user.members"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.members'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard</title>
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css" rel="stylesheet" media="screen">

    <link href="{{ url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Top Navigation Menu -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Inventory</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <!-- Sidebar Menu !-->
          <ul class="nav nav-sidebar">
            {% if current_user.is_authenticated() %}
            <li><a class="btn btn-default" style="width:100%;text-transform:uppercase;font-weight:bold;" href="{{ url_for('inventory.checkin')}}">Check In</a></li>
            <li><a class="btn btn-default" style="width:100%;text-transform:uppercase;font-weight:bold;" href="{{ url_for('inventory.checkout')}}">Check Out</a></li>
            <li><a href="{{ url_for("inventory.transactions")}}">Transactions</a></li>
            <li>
              <ul class="nav nav-sidebar-submenu">
                <li><a href="{{ url_for("inventory.transactions")}}">View</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for("inventory.view_vendor")}}">Vendors</a></li>
            <li>
              <ul class="nav nav-sidebar-submenu">
                <li><a href="{{ url_for("inventory.view_vendor")}}">View</a></li>
                <li><a href="{{ url_for("inventory.create_vendor")}}">Add</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for("inventory.view_purchase_order")}}">Purchase Orders</a></li>
            <ul class="nav nav-sidebar-submenu">
                <li><a href="{{ url_for("inventory.view_purchase_order")}}">View</a></li>
            </ul>
            <li><a href="{{ url_for("inventory.view_component") }}">Component</a></li>
            <ul class="nav nav-sidebar-submenu">
              <li><a href="{{ url_for("inventory.view_component") }}">View</a></li>
              <li><a href="{{ url_for("inventory.create_component") }}">Create</a></li>
            </ul>
            <li><a href="{{ url_for("inventory.manage_tags") }}">Manage Tags</a></li>
              {% else %}
              {% endif %}

            </ul>
        </div>
        <!-- Body Content !-->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

          <div>
            <!-- messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <br>
            <div class="row">
              <div>
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                  {{message}}
                </div>
                {% endfor %}
              </div>
            </div>
            {% endif %}
            {% endwith %}


            <!-- child template -->
            {% block content %}{% endblock %}

            <br>

            <!-- errors -->
            {% if error %}
            <p class="error"><strong>Error:</strong> {{ error }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    {% include 'footer.html' %}

    <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <!-- scripts -->
      <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
      <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
      <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
      <script>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
      </script>
      {% block js %}{% endblock %}


  </body>
</html>

app/templates/footer.html
<footer>
  <div class="container">
  </div>
</footer>

app/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Flask-Inventory</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated() %}
           <li>
               <a href="{{ url_for('inventory.view') }}" 
                  class="dropdown-toggle" data-toggle="dropdown" 
                  role="button">Vendors<span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                   <li><a href="{{ url_for('inventory.view') }}">View</a></li>
                   <li><a href="{{ url_for('inventory.register') }}">Add</a></li>
               </ul>

           </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>